name: survey_camp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  lottie: ^3.1.3
  lucide_icons: ^0.257.0
  image_picker: ^1.0.8
  permission_handler: ^11.3.1
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^5.0.0
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  path: ^1.8.3
  firebase_app_check: ^0.2.1+8
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.1
  csv: ^5.1.1
  downloads_path_provider_28: ^0.1.2

  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0
  usage_stats: ^1.3.1
  app_settings: ^6.1.1
  share_plus: ^7.2.2
  open_file: ^3.3.2
  pdf: ^3.11.3
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/poppins/
    - assets/animations/
    - lib/config/.env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
